name: podlove_flutter
description: "A new Flutter project."

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter
  http: ^1.2.2
  get: ^4.6.6
  dio: ^5.7.0
  flutter_screenutil: ^5.9.3
  device_preview: ^1.2.0
  flutter_svg: ^2.0.16
  dotted_border: 2.1.0
  shared_preferences: ^2.3.5
  cupertino_icons: ^1.0.8
  pretty_dio_logger: ^1.4.0
  go_router: ^14.6.3
  flutter_riverpod: ^2.6.1
  flutter_hooks: ^0.20.5
  hooks_riverpod: ^2.6.1
  pinput: ^5.0.1
  logger: ^2.5.0
  geolocator: ^13.0.2
  geocoding: ^3.0.0
  permission_handler: ^11.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
          weight: 400
        - asset: assets/fonts/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/Poppins-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 700
        - asset: assets/fonts/Poppins-Italic.ttf
          style: italic
  assets:
    - assets/images/background.png
    - assets/images/podLove.png
    - assets/images/google.png
    - assets/images/apple.png
    - assets/images/location.png
    - assets/images/add_a_photo.png
    - assets/images/profile-avatar.png
    - assets/images/match-1.png
    - assets/images/match-2.png
    - assets/images/match-3.png
    - assets/images/schedule.png
    - assets/images/home-icon.png
    - assets/images/match-icon.png
    - assets/images/bell-icon.png
    - assets/images/avatar-icon.png
    - assets/images/hidden-match.png
    - assets/images/revealed-match.png
    - assets/images/podcast-icon.png
    - assets/images/feedback-icon.png
    - assets/images/invite-icon.png
    - assets/images/payment-icon.png
    - assets/images/calender-icon.png
    - assets/images/upgrade-icon.png
    - assets/images/edit-icon.png
    - assets/images/camera.png
    - assets/images/tick-image.png
    - assets/images/attention.png
    - assets/images/flower.png
    - assets/images/loading.png
    - assets/images/congrats.png
    - assets/images/encrypted.png
    - assets/images/logout.png
    - assets/images/quiz.png
    - assets/images/report.png
    - assets/images/settings.png
    - assets/images/support.png
    - assets/images/podcast.jpg
    - assets/images/calendar.png
    - assets/images/hand-point.png
    - assets/images/btn-active.png
    - assets/images/btn-inactive.png
    - assets/images/match-revealed.png
    - assets/images/call.png
    - assets/images/videocam.png
    - assets/images/payment.png
    - assets/images/stripe.png
    - assets/images/message.png
  uses-material-design: true
